packages:
  - 'packages/badgers'
  - 'packages/blockpoint'
  - 'packages/catdex'
  - 'packages/common'
  - 'packages/drip'
  - 'packages/dutch'
# - 'packages/flash'
  - 'packages/future'
  - 'packages/locktime'
  - 'packages/photon'
  - 'packages/small'
  - 'packages/subscription'
  - 'packages/timeout'
  - 'packages/trust'
  - 'packages/wrap'
  - 'packages/app'
  - 'packages/wallet'
# - 'packages/*'
