name: Deploy .dev

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [23]
    steps:
    - uses: actions/checkout@v7
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - run: pnpm app:build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cname: vox.cash
        publish_dir: ./docs
